apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connection-service
  name: udaconnect-connection-service
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30003
  selector:
    service: udaconnect-connection-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connection-service
  name: udaconnect-connection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connection-service
  template:
    metadata:
      labels:
        service: udaconnect-connection-service
    spec:
      containers:
      - image: isaactps/nd064-udaconnect-connectionservice:latest
        name: udaconnect-connection-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "128m"
        livenessProbe:
          tcpSocket:
            port: 5005
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 5005
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: GRPC_VERBOSITY
          value: "DEBUG"        
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
