apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-kafka-person-consumer
  name: udaconnect-kafka-person-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-kafka-person-consumer
  template:
    metadata:
      labels:
        service: udaconnect-kafka-person-consumer
    spec:
      containers:
      - image: isaactps/nd064-udaconnect-personconsumer:latest
        name: udaconnect-kafka-person-consumer
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "128m"
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
